baseURL = 'http://localhost'
languageCode = 'en-us'
title = 'Personal Webpage'
theme = 'poison'
pluralizelisttitles = true

pagerSize = 10

# Basic Poison theme configuration
[params]
	# Sidebar content
    brand = "Theofilos Augoustis" 
    brand_image = "/images/profile-pic.png"
    description = "PhD Student @ Technical University of Munich"
    dark_mode = false

    # MENU PLACEHOLDER
    # Menu dict keys:
        # Name:         The name to display on the menu.
        # URL:          The directory relative to the content directory.
        # HasChildren:  If the directory's files should be listed.  Default is true.
        # Limit:        If the files should be listed, how many should be shown.
    menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", HasChildren = true, Limit = 5},
    ]

    # Links to socials
    github_url = "https://github.com/taugoust"
    linkedin_url = "https://linkedin.com/in/theofilos-augoustis-2b901b164"
	email_url = "mailto://theofilos.augoustis@gmail.com"

	# Enable RSS
	rss_icon = true
	rss_section = "posts"

    # Hex colors for your sidebar.
    sidebar_bg_color = "#202020"            # default is #202020
    sidebar_img_border_color = "#515151"    # default is #515151
    sidebar_p_color = "#909090"             # default is #909090
    sidebar_h1_color = "#FFF"               # default is #FFF
    sidebar_a_color = "#FFF"                # default is #FFF
    sidebar_socials_color = "#FFF"          # default is #FFF
    moon_sun_color = "#FFF"                 # default is #FFF
    moon_sun_background_color = "#515151"   # default is #515151

    # Hex colors for your content in light mode.
    text_color = "#222"             # default is #222
    content_bg_color = "#FAF9F6"    # default is #FAF9F6
    post_title_color = "#303030"    # default is #303030
    list_color = "#5a5a5a"          # default is #5a5a5a
    link_color = "#268bd2"          # default is #268bd2
    date_color = "#515151"          # default is #515151

    # Hex colors for your content in dark mode
    text_color_dark = "#eee"            # default is #eee
    content_bg_color_dark = "#121212"   # default is #121212
    post_title_color_dark = "#DBE2E9"   # default is #DBE2E9
    list_color_dark = "#9d9d9d"         # default is #9d9d9d
    link_color_dark = "#268bd2"         # default is #268bd2
    date_color_dark = "#9a9a9a"         # default is #9a9a9a

[taxonomies]
    series = 'series'
    tags = 'tags'

